---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: minecraft-server
    groups:
      - server
    image: docker.io/geerlingguy/docker-centos8-ansible
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    published_ports:
      - 0.0.0.0:${MINECRAFT_PORT:-25565}:25565/tcp
  - name: minecraft-client
    groups:
      - client
    image: python
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      server:
        motd: "Minecraft deployed in a container by Molecule"
    host_vars:
      minecraft-client:
        ansible_python_interpreter: /usr/local/bin/python
        wait_seconds: ${WAIT_SECONDS:-120}
verifier:
  name: ansible
