---
- name: Set up client
  hosts: client
  become: true
  tasks:

    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install mcstatus
      ansible.builtin.pip:
        name: mcstatus
