---
extends: existence
message: Do not use colons in headings if it is not explicitly required.
link: http://stylepedia.net/style/#colons-and-semicolons
level: warning
scope: heading
nonword: true
tokens:
  - '\w+:'
