---
extends: existence
message: Avoid gender-specific language when not necessary.
link: 'http://stylepedia.net/style/#gender-references'
level: warning
ignorecase: true
tokens:
  - him
  - her
  - she
  - he
  - his
  - hers
  - himself
  - herself
  - I
  - me
  - us
  - our
  - we
