extends: substitution
message: "Use '%s' instead of '%s'."
link: http://stylepedia.net/style/#contractions-and-abbreviations
ignorecase: true
level: error
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example
  '\b(?:ie|i\.e\.)[\s,]': that is
