---
extends: existence
message: "'%s' - Do not use slang"
link: http://stylepedia.net/style/#heading-styles
scope: text
level: warning
description: "Slang, like metaphors, should be used only occasionally if it is to have effect."
ignorecase: true
tokens:
  - administrivia
  - anything you/they like
  - at this point in time
  - automagic
  - best-of-breed
  - bleeding edge
  - bottom line
  - bucketize
  - center of competency
  - check this site
  - coopetition
  - core competency
  - eat your own dogfood
  - data point
  - dig deeper
  - delve deeper
  - double-edged sword
  - double-bladed sword
  - enterprise-ready
  - exceed your expectations
  - fib
  - flying by the seat of your pants
  - frame it up
  - frown upon
  - fuzzy
  - going-forward basis
  - happy path
  - harness the power
  - have a crack at
  - jump right in
  - if you want
  - if you wish
  - improve
  - enhance
  - in a pinch
  - infomediary
  - is designed to
  - kettle of fish
  - leverage
  - lights on
  - lights-on
  - low-hanging fruit
  - marketecture
  - meet your needs
  - mission-critical
  - net-net
  - niche focus
  - over the wire
  - pain in the backside
  - paradigm
  - performant
  - physicalize
  - piggyback
  - pre-baked
  - productize
  - ready to rumble
  - rest on your laurels
  - right before doing something
  - root your server
  - shoot yourself in the foot
  - shy of
  - silo
  - siloed
  - solutioning
  - solutions-based
  - solution stack
  - stovepipe
  - synergistic
  - synergy
  - synergical connectivity
  - to think outside the box
  - tunnel vision
  - under the covers
  - value-added
  - very
  - virtual elephants
