---
- name: install apache
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: copy html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0644'

- name: start httpd service
  ansible.builtin.systemd:
    name: httpd
    enabled: yes
    state: started
    daemon_reload: yes
