---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: centos:8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    published_ports:
      - 0.0.0.0:8080:80
provisioner:
  name: ansible
verifier:
  name: ansible
