---
dependency:
  name: galaxy
driver:
  name: podman
lint: ansible-lint
platforms:
  - name: pid001
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    published_ports:
      - 0.0.0.0:8080:80
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
