---
- name: Install dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - epel-release
  - java-1.8.0-openjdk-devel
  - rsync
  - git
  - gcc

- name: Create the minecraft user
  user:
    name: minecraft
    home: /opt/minecraft
    system: yes

- name: Ensure minecraft directories exist and permissions are correct
  file:
    path: /opt/{{ item }}
    state: directory
    owner: minecraft
    group: minecraft
    mode: 0755
  with_items:
  - minecraft
  - minecraft/backup
  - minecraft/build
  - minecraft/server

- name: Get version manifest
  uri:
    url: https://launchermeta.mojang.com/mc/game/version_manifest.json
    method: GET
  register: version_manifest

- debug:
    var: recent_release
    verbosity: 3
  vars:
    recent_release: '{{ version_manifest.json.versions | selectattr("id", "eq", version_manifest.json.latest.release) | list }}'

- name: Get most recent release to download
  uri:
    url: '{{ recent_release.url }}'
    method: GET
  vars:
    recent_release: '{{ (version_manifest.json.versions | selectattr("id", "equalto", version_manifest.json.latest.release) | list).0 }}'
  register: latest_version_manifest

- debug:
    var: latest_version_manifest
    verbosity: 3

- name: Download latest Minecraft release
  get_url:
    url: '{{ latest_version_manifest.json.downloads.server.url }}'
    dest: /opt/minecraft/server/server.jar

- name: Clone mcrcon repo
  git:
    repo: https://git.code.sf.net/p/mcrcon/code
    dest: /opt/minecraft/build/mcrcon-code
    version: master

- name: Build mcrcon binary
  command: gcc mcrcon.c -o mcrcon
  args:
    chdir: /opt/minecraft/build/mcrcon-code
    creates: /opt/minecraft/build/mcrcon-code/mcrcon

- name: Copy mcrcon binary to proper location
  copy:
    remote_src: yes
    src: /opt/minecraft/build/mcrcon-code/mcrcon
    dest: /opt/minecraft/mcrcon
    mode: 0755
    owner: minecraft
    group: minecraft

- name: Create minecraft unit file
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service

- name: Populate minecraft server.properties
  template:
    src: server.properties.j2
    dest: /opt/minecraft/server/server.properties

- name: Agree to the EULA
  copy:
    content: |
      eula=true
    dest: /opt/minecraft/server/eula.txt

- name: Enable and start the minecraft service
  systemd:
    name: minecraft
    state: started
    enabled: yes
    daemon_reload: yes