---
name: Ansible Lint
on: [push]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: 'ansible-lint Ansible Playbook'
        uses: ansible-community/ansible-lint-action@main
        with:
          targets: ""
          args: "--exclude .github/"
