---
name: Ansible Lint
on: [push]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'ansible-lint Ansible Playbook'
        uses: ansible/ansible-lint-action@master
        with:
          targets: ""
          args: "--exclude .github/"
