---
name: Vale
on: [push, pull_request]

jobs:

  vale:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'run vale'
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["minecraft/", "README.md", "web/"]'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
