---
name: 'Yamllint GitHub Actions'
on: [push, pull_request]

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'yamllint Ansible Playbook'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .
          yamllint_strict: false
          yamllint_comment: false
          yamllint_config_filepath: '.yamllint'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
